AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Consumer stack for event-driven transactions, referencing an existing SQS queue.

Globals:
  Function:
    Runtime: provided.al2
    MemorySize: 128
    Timeout: 10
    Architectures:
      - x86_64

Parameters:
  TransactionQueueARN:
    Type: String
    Description: ARN of the SQS queue holding transaction messages

  ResponseQueueArn:
    Type: String
    Description: ARN of the SQS queue holding response messages

  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table
    Default: Transactions

  DynamoDBEndpoint:
    Type: String
    Description: DynamoDB endpoint (e.g., http://localhost:8000 for local tests)
    Default: https://dynamodb.us-east-1.amazonaws.com

  AWSRegion:
    Type: String
    Description: AWS region where resources should be deployed
    Default: us-east-1

  QueueUrl:
    Type: String
    Description: URL of the SQS queue
    Default: https://sqs.us-east-1.amazonaws.com/140023383737/Bank_Transactions

Resources:
  ########################################
  # (1) DynamoDB Table
  ########################################
  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: AccountID
          AttributeType: S
        - AttributeName: TransactionID
          AttributeType: S
        - AttributeName: PhoneNumber   # ADD THIS
          AttributeType: S
      KeySchema:
        - AttributeName: AccountID
          KeyType: HASH
        - AttributeName: TransactionID
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      GlobalSecondaryIndexes:
        - IndexName: PhoneNumberIndex
          KeySchema:
            - AttributeName: PhoneNumber
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ########################################
  # (2) SNS Topic for Fraud Alerts
  ########################################
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: FraudAlerts

  ########################################
  # (3) TransactionPipelineFunction
  ########################################
  TransactionPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TransactionPipelineFunction
      CodeUri: ../
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DescribeTable
              Resource: !GetAtt TransactionsTable.Arn
            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
              Resource: !Ref TransactionQueueARN
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:140023383737:secret:greenflags/twilio-*
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref TransactionQueueARN
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5
    Metadata:
      BuildMethod: makefile

  ########################################
  # (4) FraudPipelineFunction
  ########################################
  FraudPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FraudPipelineFunction
      CodeUri: ../
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DescribeTable
              Resource: !GetAtt TransactionsTable.Arn
            - Effect: Allow
              Action:
                - sns:CreateTopic
                - sns:Subscribe
                - sns:Publish
              Resource: !Ref NotificationTopic
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:140023383737:secret:greenflags/twilio-*
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt TransactionsTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5
    Metadata:
      BuildMethod: makefile
  # ########################################
  # # (5) SQS Queue and ResponsePipelineFunction
  # ########################################

  ResponsePipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ResponsePipelineFunction
      CodeUri: ../
      Handler: bootstrap 
      Runtime: provided.al2
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref DynamoDBTableName
      EphemeralStorage:
        Size: 512

      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:DescribeTable
                - dynamodb:Query 
              Resource: 
                - !GetAtt TransactionsTable.Arn
                - !Sub "${TransactionsTable.Arn}/index/PhoneNumberIndex"

            - Effect: Allow
              Action:
                - sqs:ReceiveMessage
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:SendMessage
              Resource: !Ref ResponseQueueArn
            - Effect: Allow
              Action:
                - sns:CreateTopic
                - sns:Subscribe
                - sns:Publish
              Resource: !Ref NotificationTopic
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: arn:aws:secretsmanager:us-east-1:140023383737:secret:greenflags/twilio-*
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref ResponseQueueArn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 5
    Metadata:
      BuildMethod: makefile
  


Outputs:
  DynamoDBTableNameOut:
    Description: "Name of the DynamoDB table"
    Value: !Ref TransactionsTable

  NotificationTopicArn:
    Description: "ARN of the SNS topic"
    Value: !Ref NotificationTopic

  TransactionPipelineArn:
    Description: "ARN of the TransactionPipelineFunction"
    Value: !GetAtt TransactionPipelineFunction.Arn

  FraudPipelineArn:
    Description: "ARN of the FraudPipelineFunction"
    Value: !GetAtt FraudPipelineFunction.Arn

  ResponsePipelineArn:
    Description: "ARN of the ResponsePipelineFunction"
    Value: !GetAtt ResponsePipelineFunction.Arn
